### ISSUE TITLE
Fix ECS Task bug error with sentiment analyser image

### ISSUE THREAD

**Issue by YakMan101** [indiah444/Media-Polarisation-Project#112]
As a developer I want to fix the psycopg import bug so that I can have a functioning sentiment analysis workflow

This error crops up on ECS fargate:
ImportError: /usr/local/lib/python3.13/site-packages/psycopg2/_psycopg.cpython-313-x86_64-linux-gnu.so: undefined symbol: _PyInterpreterState_Get

**Comment by megansam5** [comment]
We could check if this is solved by installing psycopg2-binary instead of psycopg2
