### ISSUE TITLE
⠀

### ISSUE THREAD

**Issue by mehrdadhalali** [indiah444/Media-Polarisation-Project#207]
As a [user], I would like to [action] so that [result] 

**User end goal**: What is the end goal of this issue?

**Acceptance Criteria**: Outline of functionality requirements, required test coverage, updates to documentation needed etc. Essentially, how do we know that the issue is ready to close?

**Comment by megansam5** [comment]
Not sure what we are trying to achieve here?

**Comment by ayahusseini** [comment]
locking this conversation because of no response
